name: ghostfolio_build
services:
  ghostfolio:
    build: ../
    image: ghostfolio/ghostfolio:local
    extends:
      file: docker-compose.yml
      service: ghostfolio

  postgres:
    container_name: gf-postgres-build
    extends:
      file: docker-compose.yml
      service: postgres
    volumes:
      - type: bind
        source: ${HOME}/data/ghostfolio/postgres
        target: /var/lib/postgresql/data

  redis:
    container_name: gf-redis-build
    extends:
      file: docker-compose.yml
      service: redis
